server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Amar722@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: HOTEL-SERVICE
  

eureka:
  instance: 
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-38792313.okta.com/oauth2/default
    audience: api://default
    
    
    