server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Amar722@
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-38792313.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oage76axcSiv7prD5d7
            client-secret: byMjPPgZ0ZvewQbZMAkFUs7u77LoNL6q93HrrT9gdEfzXdqLHtR0ENFpVCvN_LTD
        provider:
          okta:
            issuer-uri: https://dev-38792313.okta.com/oauth2/default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints: 
    web:
      exposure: 
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 4s
  ratelimiter:
    instances:
      userRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 2s

okta:
  oauth2:
    issuer: https://dev-38792313.okta.com/oauth2/default
    audience: api://default



# resilience4j.circuitbreaker.configs.shared.register-health-indicator=true
# resilience4j.circuitbreaker.configs.shared.sliding-window-type=count_based
# resilience4j.circuitbreaker.configs.shared.sliding-window-size=5
# resilience4j.circuitbreaker.configs.shared.failure-rate-threshold=40
# resilience4j.circuitbreaker.configs.shared.slow-call-rate-threshold=40
# resilience4j.circuitbreaker.configs.shared.permitted-number-of-calls-in-half-open-state=1
# resilience4j.circuitbreaker.configs.shared.max-wait-duration-in-half-open-state=10s
# resilience4j.circuitbreaker.configs.shared.wait-duration-in-open-state=10s
# resilience4j.circuitbreaker.configs.shared.slow-call-duration-threshold=2s
# resilience4j.circuitbreaker.configs.shared.writable-stack-trace-enabled=true
# resilience4j.circuitbreaker.configs.shared.automatic-transition-from-open-to-half-open-enabled=true




# eureka:
#   instance: 
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/

  